package org.hse.software.construction.model.report;

import org.hse.software.construction.model.task.Task;

public class TaskReport implements Reportable {
    private Task task;

    public TaskReport(Task task) {
        this.task = task;
    }

    @Override
    public String getReport() {
        // Add logic to generate report for task
        return "Task: " + task.getTitle() +
                ", Assigned to: " + (task.getAssignedEmployee() != null ? task.getAssignedEmployee().getName() : "Unassigned") +
                ", Completed: " + task.getState().name() + " - This report is generated by TaskReportDecorator";
    }
}


